openapi: 3.0.3
info:
  title: Read management system Frontend API
  description: Read management system Frontend API
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /tolls/{userUUID}:
    get:
      operationId: getNotPaidTolls
      tags:
        - Toll
      summary: Get users not payed tolls
      description: Get users not payed tolls
      parameters:
        - name: userUUID
          in: path
          schema:
            type: string
            format: uuid
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NotPayedToll'
  /tolls/{tollId}/payments:
    post:
      operationId: payToll
      tags:
        - Toll
      summary: Pay toll
      description: Pay toll
      parameters:
        - name: tollId
          description: toll id
          in: path
          schema:
            type: integer
            format: int64
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/URL'

  /tolls/subscription:
    get:
      operationId: getSubscriptionInfo
      tags:
        - Subscription
      summary: Get subscription info
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref:
                  '#/components/schemas/Subscription'
  /fees/history/{userUUID}:
    get:
      operationId: getUsersFee
      tags:
        - Fees
      summary: Get fees history
      description: Get fees history
      parameters:
        - name: userUUID
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fee'



  /penalty/{userUUID}:
    get:
      operationId: getAllPenalties
      tags:
        - Penalties
      summary: Get user's penalties
      description: Get user's penalties
      parameters:
        - name: userUUID
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Penalty'
        404:
          description: Not found

  /tariff:
    get:
      operationId: getAllTariffs
      tags:
        - Tariffs
      summary: Get all tariffs
      description: Get all tariffs
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TariffSimplified'

    post:
      operationId: addTariff
      tags:
        - Tariffs
      summary: Add tariff
      description: Add tariff
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tariff'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tariff'
        400:
          description: Bad request

  /tariff/{tariffId}:
    get:
      operationId: getTariff
      tags:
        - Tariffs
      summary: Get particular tariff
      description: Get particular tariff
      parameters:
        - name: tariffId
          in: path
          schema:
            type: integer
            format: int64
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tariff'
        404:
          description: Not found

    put:
      operationId: updateTariff
      tags:
        - Tariffs
      summary: Update tariff
      description: Update tariff
      parameters:
        - name: tariffId
          in: path
          schema:
            type: integer
            format: int64
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tariff'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tariff'
        404:
          description: Not found
        400:
          description: Bad request

    delete:
      operationId: deleteTariff
      tags:
        - Tariffs
      summary: Delete tariff
      description: Delete tariff
      parameters:
        - name: tariffId
          in: path
          schema:
            type: integer
            format: int64
          required: true
      responses:
        200:
          description: OK
        404:
          description: Not found


components:
  schemas:
    NotPayedToll:
      type: object
      properties:
        tollId:
          type: integer
          format: int64

    PayedToll:
      type: object

    SubscriptionInfo:
      type: object
      properties:
        costPerMonth:
          type:
            number
          format:
            double

    Subscription:
      type: object
      properties:
        id:
          type: integer
          format: int64
        subscriberId:
          type: string
          format: uuid
        from:
          type: string
          format: date
        to:
          type: string
          format: date
      required:
        - id
        - subscriberId
        - from
        - to
    Fee:
      properties:
        id:
          type: integer
          format: int64
        paymentDate:
          type: string
          format: date
        feeAmount:
          type: number
          format: double
      required:
        - id
        - paymentDate
        - feeAmount

    URL:
      type: object

    Localization:
      type: object
      properties:
        id:
          type: integer
          format: int64
        latitude:
          type: string
        longitude:
          type: string
      required:
        - latitude
        - longitude

    VehicleType:
      type: string
      enum: [car, truck, motorcycle, other]

    Vehicle:
      type: object
      properties:
        id:
          type: integer
          format: int64
        vehicleType:
          type: string
          format: VehicleType
        make:
          type: string
        model:
          type: string
        productionYear:
          type: integer
          minimum: 1800
          maximum: 2050
        registrationNumber:
          type: string
        length:
          description: Length in meters
          type: number
          format: double
          minimum: 0.0
        width:
          description: Width in meters
          type: number
          format: double
          minimum: 0.0
        height:
          description: Height in meters
          type: number
          format: double
          minimum: 0.0
        weight:
          description: Weight in kilograms
          type: number
          format: double
          minimum: 0.0
        engineVolumeCm3:
          type: integer
          minimum: 0
      required:
        - vehicleType
        - make

    Passing:
      type: object
      properties:
        id:
          type: integer
          format: int64
        payable:
          type: boolean
        dateTime:
          type: string
          format: date-time
        localization:
          type: object
          format: Localization
        vehicle:
          type: object
      required:
        - payable
        - dateTime
        - localization
        - vehicle

    Penalty:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: string
          format: uuid
        description:
          type: string
        passing:
          type: object
        paid:
          type: boolean
      required:
        - passing
        - paid

    Tariff:
      type: object
      properties:
        id:
          type: integer
          format: int64
        active:
          type: boolean
        name:
          type: string
        prices:
          type: object
          additionalProperties:
            type: number
            format: double
            minimum: 0.0
      required:
        - active
        - name
        - prices

    TariffSimplified:
      type: object
      properties:
        id:
          type: integer
          format: int64
        active:
          type: boolean
        name:
          type: string
      required:
        - active
        - name